version: "3.6"
services:
  database:
    container_name: estock_dev_database
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=estock
      - POSTGRES_USER=estock
      - POSTGRES_PASSWORD=estock

  mail:
    container_name: estock_dev_mail
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"
