app:
  name: ${ESTOCK_APP_NAME:EStock}
  stock:
    base-url: https://www.boursorama.com/cours
    daily-report:
      # At 19:00 on every day-of-week from Monday through Friday.
      cron: ${ESTOCK_STOCK_DAILY_REPORT_CRON:0 19 * * 1-5}

  mail:
    sender: ${ESTOCK_MAIL_SENDER}
    receiver: ${ESTOCK_MAIL_RECEIVER}
    stock:
      daily-report:
        subject: ${ESTOCK_MAIL_STOCK_DAILY_REPORT_SUBJECT:Daily report}

spring:
  devtools:
    add-properties: false

  datasource:
    url: jdbc:${ESTOCK_DATABASE:postgresql}://${ESTOCK_DATABASE_HOST:localhost}:${ESTOCK_DATABASE_PORT:5432}/${ESTOCK_DATABASE_NAME:estock}
    username: ${ESTOCK_DATABASE_USER}
    password: ${ESTOCK_DATABASE_PASSWORD}
    driver-class-name: ${ESTOCK_DATABASE_DRIVER:org.postgresql.Driver}

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml

  mail:
    host: ${ESTOCK_MAIL_HOST}
    port: ${ESTOCK_MAIL_PORT}
    username: ${ESTOCK_MAIL_USERNAME}
    password: ${ESTOCK_MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        smtp:
          auth: ${ESTOCK_MAIL_SMTP_AUTH_ENABLED}
          starttls:
            enable: ${ESTOCK_MAIL_SMTP_TLS_ENABLED}
