app:
  mail:
    sender: noreply@estock-test.com
    receiver: test@test.com

spring:
  devtools:
    add-properties: true

  datasource:
    username: estock
    password: estock

  liquibase:
    change-log: classpath:/db/changelog-dev/master.xml

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        debug: true
        smtp:
          auth: false
          starttls:
            enable: false
